### ISSUE TITLE
output: gender "C"

### ISSUE THREAD

**Issue by nikita-moor** [ArchimedesDigital/open_words#10]
Gender of the word "rebus" < [rēs, reī](https://en.wiktionary.org/wiki/res#Latin) is feminine. `open_words` outputs "C" gender, what does it mean?

```json
[
  {
    "word": "rebus",
    "defs": [
      {
        "orth": [
          "res",
          "re"
        ],
        "senses": [
          "thing",
          "event/affair/business",
          "fact",
          "cause",
          "property",
          "[~ familiaris => property]"
        ],
        "infls": [
          {
            "ending": "ebus",
            "pos": "noun",
            "form": {
              "declension": "dative",
              "number": "plural",
              "gender": "C"
            }
          },
          {
            "ending": "ebus",
            "pos": "noun",
            "form": {
              "declension": "ablative",
              "number": "plural",
              "gender": "C"
            }
          }
        ]
      }
    ]
  }
]
```

P.S. Also, `orth` group seems incorrect in this example.

**Comment by air-wreck** [comment]
As a gender, "C" probably refers to common gender, indicating that a noun can take the masculine or feminine (see [canis](https://en.wiktionary.org/wiki/canis#Latin), for instance). You can see similar behavior in the original [Words](http://archives.nd.edu/cgi-bin/wordz.pl?keyword=canis) (see the last definition).

It is weird that `open_words` outputs "C" for "rebus," since the original Words appears to give [this](http://archives.nd.edu/cgi-bin/wordz.pl?keyword=rebus).

**Comment by nikita-moor** [comment]
You are right, it's from  [Words/inflections_package.ads](https://github.com/dsanson/Words/blob/4fa2c86a294722fb1df6dfe3b538d44fb18ec224/inflections_package.ads#L82-L88):

```ada
type GENDER_TYPE is (
        X,         --  all, none, or unknown
        M,         --  Masculine
        F,         --  Feminine
        N,         --  Neuter
        C          --  Common (masculine and/or feminine)
                     );
```
