### ISSUE TITLE
is the morphological information documented anywhere?

### ISSUE THREAD

**Issue by jtauber** [ArchimedesDigital/open_words#7]
As a morphologist doing related work on Greek, I'd like to better understand what various fields in Whitaker's data mean (or, if you prefer, what various fields in `data.json` mean).

It's clear what `pos`, parts`, `senses`, and `orth` mean but are `n` and `form` documented somewhere?

**Comment by lukehollis** [comment]
Hi @jtauber, thanks for asking--this is a good question. `n` and `form` are vestiges of the original codebase using a lookup system for word forms. I need to update this port of the original Ada code so that it is fully functional, but for the moment William Whitaker's original documentation will offer the best explanation of everything from the source--though it's not stated explicitly in his documentation, I believe this is the guide to what you're looking for: 
https://github.com/dsanson/Words/blob/master/INFLECTS.LAT#L53


Also you can check out his explanation:
https://github.com/dsanson/Words/blob/master/wordsdoc.htm#L557 
and the other original source files: 
https://raw.githubusercontent.com/dsanson/Words/master/STEMLIST.GEN
https://github.com/dsanson/Words/blob/master/UNIQUES.LAT

I did most of the data transformation work (albeit imperfect) of these files here: https://github.com/segetes/open_words/blob/master/open_words/format_data.py#L201
